### ISSUE TITLE
Long char arrays won't work

### ISSUE THREAD

**Issue by nielsvdn** [electric-sheep-co/arduino-redis#31]
Hello,

I want to write images to my redis database from my ESP32 CAM, but when I SET a key with as value a base64 image and open the key it returns " b' ' " instead of the long char array string. Things I have tried:

- Printing the string to the serial monitor and check if the string is not empty. It wil display the long string
- Write the long string with python on my pc to redis. This works.
- Setting a small char string to redis. this works

My code:
`#include <Redis.h>

#include "esp_camera.h"
#include <WiFi.h>
#include "esp_timer.h"
#include "img_converters.h"
#include "Arduino.h"
#include "fb_gfx.h"
#include "soc/soc.h" //disable brownout problems
#include "soc/rtc_cntl_reg.h"  //disable brownout problems
extern "C" {
#include "crypto/base64.h"
}

// SETTINGS
const char* ssid = "Marlex-ap";
const char* password = "My wifi passowrd";
#define REDIS_ADDR      "84.247.9.119"
#define REDIS_PORT      6379
#define REDIS_PASSWORD  "MY PASSWORD"

// SET CAMERA MODEL AI_THINKER
#define PWDN_GPIO_NUM     32
#define RESET_GPIO_NUM    -1
#define XCLK_GPIO_NUM      0
#define SIOD_GPIO_NUM     26
#define SIOC_GPIO_NUM     27

#define Y9_GPIO_NUM       35
#define Y8_GPIO_NUM       34
#define Y7_GPIO_NUM       39
#define Y6_GPIO_NUM       36
#define Y5_GPIO_NUM       21
#define Y4_GPIO_NUM       19
#define Y3_GPIO_NUM       18
#define Y2_GPIO_NUM        5
#define VSYNC_GPIO_NUM    25
#define HREF_GPIO_NUM     23
#define PCLK_GPIO_NUM     22

// DEFINE FUNCTION TO TAKE A IMAGE AND SEND IT TO REDIS
void takeImageAndSendToRedis(){
  // test
}

// RUN SETUP
void setup() {

  // DISABLE BROWNOUT DETECTOR
  WRITE_PERI_REG(RTC_CNTL_BROWN_OUT_REG, 0);

 // START SERIAL COMMINUCATION
  Serial.begin(115200);
  Serial.setDebugOutput(false);

  // CONFIG CAMERA MODULE
  camera_config_t config;
  config.ledc_channel = LEDC_CHANNEL_0;
  config.ledc_timer = LEDC_TIMER_0;
  config.pin_d0 = Y2_GPIO_NUM;
  config.pin_d1 = Y3_GPIO_NUM;
  config.pin_d2 = Y4_GPIO_NUM;
  config.pin_d3 = Y5_GPIO_NUM;
  config.pin_d4 = Y6_GPIO_NUM;
  config.pin_d5 = Y7_GPIO_NUM;
  config.pin_d6 = Y8_GPIO_NUM;
  config.pin_d7 = Y9_GPIO_NUM;
  config.pin_xclk = XCLK_GPIO_NUM;
  config.pin_pclk = PCLK_GPIO_NUM;
  config.pin_vsync = VSYNC_GPIO_NUM;
  config.pin_href = HREF_GPIO_NUM;
  config.pin_sscb_sda = SIOD_GPIO_NUM;
  config.pin_sscb_scl = SIOC_GPIO_NUM;
  config.pin_pwdn = PWDN_GPIO_NUM;
  config.pin_reset = RESET_GPIO_NUM;
  config.xclk_freq_hz = 20000000;
  config.pixel_format = PIXFORMAT_JPEG; 

  // SET PICTURE QUALITY
  if(psramFound()){
    config.frame_size = FRAMESIZE_UXGA;
    config.jpeg_quality = 50;
    config.fb_count = 2;
  } else {
    config.frame_size = FRAMESIZE_SVGA;
    config.jpeg_quality = 52;
    config.fb_count = 1;
  }
  
  // MOUNT CAMERA
  esp_err_t err = esp_camera_init(&config);

  // CHECK IF CAMERA MOUNTED CORRECTLY
  if (err != ESP_OK) {
    Serial.printf("Camera init failed with error 0x%x", err);
    return;
  }

  
  // START WIFI CONNECTION
  WiFi.begin(ssid, password);

  // PRINT DOTS WHILE CONNECTING
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }

  // PRINT INFORMATION
  Serial.println("");
  Serial.println("WiFi connected");
  Serial.print("Camera Stream Ready! Go to: http://");
  Serial.print(WiFi.localIP());

  // CONNECT TO REDIS
  WiFiClient redisConn;
  if (!redisConn.connect(REDIS_ADDR, REDIS_PORT))
  {
      Serial.println("Failed to connect to the Redis server!");
  }

  // AUTHENTICATE WITH REDIS
  Redis redis(redisConn);
  auto connRet = redis.authenticate(REDIS_PASSWORD);

  // CHECK IF CONNECTED WITH REDIS
  if (connRet == RedisSuccess)
  {
      Serial.println("Connected to the Redis server!");
  } 
  else 
  {
      Serial.printf("Failed to authenticate to the Redis server! Errno: %d\n", (int)connRet);
  }

  // TAKE AND SEND IMAGE
  // SET VARS
  camera_fb_t * fb = NULL;
  esp_err_t res = ESP_OK;
  size_t _jpg_buf_len = 0;
  uint8_t * _jpg_buf = NULL;
  
  // Take IMAGE
  fb = esp_camera_fb_get();

  // CHECK IF SUCCES
  if (!fb) {
    Serial.println("Camera capture failed");
    
  // GET IMAGE
  } else {
    // SKIP IMAGES UNDER 400 width
    if(fb->width > 400){
      _jpg_buf_len = fb->len;
      _jpg_buf = fb->buf;
    }
  }

  // ENCODE IMAGE
  size_t output_length; // note *NOT* a pointer
  unsigned char * encoded = base64_encode((const unsigned char *)_jpg_buf, _jpg_buf_len, &output_length);
  const char* encoded_const = (const char*)(char*)encoded;

  // PRINT IMAGE IN BASE64
  Serial.println(encoded_const);

  // WRITE IMAGE TO REDIS
  redis.set("webcam1234", encoded_const);

  // CLEAR VARS
  free(encoded);
  if(fb){
    esp_camera_fb_return(fb);
    fb = NULL;
    _jpg_buf = NULL;
  } else if(_jpg_buf){
    free(_jpg_buf);
    _jpg_buf = NULL;
  }
}

// RUN LOOP
void loop() {
  
}`

**Comment by rpj** [comment]
Hi @nielsvdn, thanks for your report & apologies things aren't working as expected for you.

Could you please build a minimal example reproducing this issue? I'm unable to use your full program as a reproducing case and cannot fix what I cannot reproduce myself.

Thanks!
