### ISSUE TITLE
Detect server disconnection during subscribe

### ISSUE THREAD

**Issue by goebish** [electric-sheep-co/arduino-redis#33]
Hi,

I've an issue with redis subscribe, it doesn't detect when the server disconnects and is then stuck waiting for messages that never happens, even if the server reconnects (since the client would have to subscribe again).

Any way to detect that and exit the subscribe message handler to attempt reconnecting to the server?

I've already used yarl with ESP-IDF but I'm using the Arduino lib for this project (on ESP32) and your lib is so much simpler to use!

Thanks!

edit: I ended up using yarl in the arduino environment, but I'd still prefer using your library ;)

**Comment by VisanXJ** [comment]
I hava a same program as @goebish ,  Is there any solution to solve it?

**Comment by VisanXJ** [comment]
I have a idea, we can write funciton for subscribe as a callback function then we can hanle network disconnect in loop function.  But i have no idea to write it. Can Someone direct me?

**Comment by rpj** [comment]
Hi @goebish & @VisanXJ, thank you for the kind words and for using the library! Also, thank you _very_ much for discovering this _massive_ oversight in the API! It is my mistake for having missed it in the first implementation of subscriber support, in all honesty. My apologies for taking awhile to look into it, real life is always getting in the way 😄 

I'm happy to report that I've found a way to implement this and have tested it successfully in limited fashion already. The code is available on [this branch](https://github.com/electric-sheep-co/arduino-redis/tree/u/rpj/issue-33) right now: you can simply check that branch out in place of the folder in your Arduino libraries folder to take advantage of it. 

You'll note that there is a new return value for `startSubscribing()`, specifically [`RedisSubscribeServerDisconnected`](https://github.com/electric-sheep-co/arduino-redis/blob/u/rpj/issue-33/Redis.h#L38). The [refactored example](https://github.com/electric-sheep-co/arduino-redis/blob/u/rpj/issue-33/examples/Subscribe/Subscribe.ino) checks [for this return value](https://github.com/electric-sheep-co/arduino-redis/blob/u/rpj/issue-33/examples/Subscribe/Subscribe.ino#L116) and [interprets it as a retry-able failure](https://github.com/electric-sheep-co/arduino-redis/blob/u/rpj/issue-33/examples/Subscribe/Subscribe.ino#L52), entering into [a backoff loop to attempt reconnection](https://github.com/electric-sheep-co/arduino-redis/blob/u/rpj/issue-33/examples/Subscribe/Subscribe.ino#L42-L47).

I'll try to get this fully tested and released to the Arduino Library manager within the next few days, and once I've done that will close out this issue to notify you that it is available in the library manager.

Thank you again for using this library & for your great feedback. It really is appreciated!

P.S.
Also @goebish, when you said you'd "already used yarl with ESP-IDF", are you speaking of [_this_ `yarl`](https://github.com/electric-sheep-co/yarl)?

**Comment by goebish** [comment]
Yes, this one, I created a Task with a subscribe thread, I didn't realize you were the author as well!

Thank you for your work on those libs.

**Comment by goebish** [comment]
I had a look at my history and noticed I had to hack yarl when I used it for the first time (10 months ago) because I already had an issue with server disconnection.
I replaced this assert in connection.c:
`assert(readBytes == sizeof(typeChar));`
with:
```
if(readBytes != sizeof(typeChar))
        return rObj;
```

**Comment by rpj** [comment]
@goebish It's really exciting to hear that you've been using `yarl` but also a bit embarrassing I must admit, as I didn't know anyone else was using that library but myself so never put any significant effort into cleaning it up. If I may ask, how did you find it initially?

Either way, you are definitely correct that `yarl` is a less user-friendly interface than this library, as again I never focused on it. My long-term goal was always to have a single "heavy lifting" library (which would be `yarl`) and then a thin facade in C++/Arduino on top of that (which is what this library would morph into). Maybe someday that will come to pass and they'll be the same 😄 

Finally: that issue you found in `connection.c` of yarl is _absolutely_ a bug that should be fixed: _excellent_ find & fix! You're more than welcome to fix it in a PR to `yarl` which I'll review & approve immediately, but if you don't feel like dealing with that, I'll absolutely make that fix you suggest to the code-base soon.

Thank you again for your wonderful feedback & fixes, and of course for using the libraries! You rock! 🤘

**Comment by goebish** [comment]
Honestly I don't remember how I found the lib initially (probably by googling or github search ?)

I used it first in an ISP-IDF ESP32-Cam project that scans QRCodes and send them to a Redis server running on a raspberry (not a good idea in the end, ESP32 isn't fast enough for a good experience and requires a better camera than the one provided in the kit to be useful).

Now I'm using the lib for another project, it's been running (subscribe + publish, in separate Tasks) for a few days without any issues :)

If you think that's an acceptable fix I'll make a PR 👍

**Comment by rpj** [comment]
@goebish Well however you found these libraries, I'm very glad you did! As noted on the PR, I've merged [#1](https://github.com/electric-sheep-co/yarl/pull/1) and added you with write access to the `yarl` project. Your contribution is truly appreciate!

(Also thanks a bunch for the note about it running well for multiple days... my personal usage has so far been the only "data point" I have to back up the stability of this library. Now I have two data points: a 100% increase! 😆)

**Comment by rpj** [comment]
Resolved by #34 and released as version [2.3.0](https://github.com/electric-sheep-co/arduino-redis/releases/tag/2.3.0)! (This release will appear in the Arduino Library Manager in about 12-24 hours, based on my previous experiences)
