### ISSUE TITLE
Compiler warnings

### ISSUE THREAD

**Issue by nottledim** [electric-sheep-co/arduino-redis#36]
I've just updated my everything Arduino and redis is now provoking compiler warnings like:
```
sketchbook/libraries/Redis_for_Arduino/Redis.cpp: In member function 'bool Redis::lset(const char*, int, const char*)':
sketchbook/libraries/Redis_for_Arduino/Redis.cpp:143:1: warning: no return statement in function returning non-void [-Wreturn-type]
 }
 ^
sketchbook/libraries/Redis_for_Arduino/Redis.cpp: In member function 'bool Redis::ltrim(const char*, int, int)':
sketchbook/libraries/Redis_for_Arduino/Redis.cpp:148:1: warning: no return statement in function returning non-void [-Wreturn-type]
 }
```
There may be other similar.

**Comment by rpj** [comment]
Thank you very much for reporting this @nottledim! 

I've fixed the underlying cause of those warnings appropriately in [version 2.4.1](https://github.com/electric-sheep-co/arduino-redis/releases/tag/2.4.1).

It takes the Arduino library manager some time (usually around 48 hours) to discover a new release and update accordingly, so you should see this new version available directly from the library manager within that time. Thanks again!
