### ISSUE TITLE
Lists (LINDEX, LINSERT, LLEN, LPOP, LPUSH, ...)

### ISSUE THREAD

**Issue by rpj** [electric-sheep-co/arduino-redis#6]
Subtask of #2

**Comment by rpj** [comment]
This is a current work-in-progress. There is an [implementation](https://github.com/electric-sheep-co/arduino-redis/blob/rpj/no-6/Redis.h#L223) of the [`LRANGE`](https://redis.io/commands/LRANGE) command [on a branch](https://github.com/electric-sheep-co/arduino-redis/tree/rpj/no-6) that, while not very "Arduino-y", does work.

**Comment by rpj** [comment]
`LRANGE` support has been [added](http://arduino-redis.com/classRedis.html#a4d6bf9e348fc7318e93bd0e76fc22917) as of [version 2.1.1](https://github.com/electric-sheep-co/arduino-redis/releases/tag/2.1.1). Will get the rest of the list-related commands added ASAP.

**Comment by sprior** [comment]
Are list operations still in the works?

**Comment by rpj** [comment]
[2.4.0](https://github.com/electric-sheep-co/arduino-redis/releases/tag/2.4.0)

**Comment by sprior** [comment]
Thanks!
