### ISSUE TITLE
'dynamic_cast' not permitted

### ISSUE THREAD

**Issue by nafraf** [electric-sheep-co/arduino-redis#72]
Hi, after updating the code to version 2.6.2, master branch, trying to compile ``Simple.ino`` or any other example, I'm getting the following error:
```sh
/home/user/Arduino/libraries/arduino-redis/RedisInternal.cpp: In member function 'RedisArray::operator std::vector<String>() const':
/home/user/Arduino/libraries/arduino-redis/RedisInternal.cpp:76:72: error: 'dynamic_cast' not permitted with -fno-rtti
             for (auto append_inner : dynamic_cast<RedisArray*>(ro.get())->operator std::vector<String>())
```
Is it a bug? or maybe a problem with my environment?
Thanks

**Comment by rpj** [comment]
Hey @nafraf, nope that was just a mistake on my part, I forgot that the environment we operate under is quite restrictive indeed. I'll get this fixed ASAP, thanks a ton for flagging it!

**Comment by rpj** [comment]
@nafraf v2.6.3 will have the fix but it's on master now if you want to just pull that. Apologies & thanks again for flagging it! It's much appreciated 🙇

**Comment by junghyun-kim** [comment]
Hi!
I had a same issue. I could build the code with`-frtti` build flag successfully. You may need `-fexceptions` flag also.
